spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cipherlock
    username: root
    password: $7-pL_NzDDd43!p&
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace
